In [ ]:
import pandas as pd

#read in the beta values for each dataset
GSE37754_df = pd.read_csv('GSE37754_betas.csv', index_col=0)
GSE49149_df = pd.read_csv('GSE49149_betas.csv', index_col=0)
GSE52068_df = pd.read_csv('GSE52068_betas.csv', index_col=0)
GSE59157_df = pd.read_csv('GSE59157_betas.csv', index_col=0)
GSE77955_df = pd.read_csv('GSE77955_betas.csv', index_col=0)

In [ ]:
#cg intersection calculation
set1=set(GSE37754_df.index.tolist())
set2=set(GSE49149_df.index.tolist())
set3=set(GSE52068_df.index.tolist())
set4=set(GSE59157_df.index.tolist())
set5=set(GSE77955_df.index.tolist())

cg_intersection = list(set1.intersection(set2, set3, set4, set5))
# Display the result
print("Intersection length of the sets:", len(cg_intersection)) #402496   #without GSE49149_df it would be 485512 (but it contain 196 important samples)

Intersection length of the sets: 402496

In [77]:
#KEEPING ONLY THE COMMON CPG SITES
GSE37754_df = GSE37754_df.loc[cg_intersection]
GSE49149_df = GSE49149_df.loc[cg_intersection]
GSE52068_df = GSE52068_df.loc[cg_intersection]
GSE59157_df = GSE59157_df.loc[cg_intersection]
GSE77955_df = GSE77955_df.loc[cg_intersection]

In [78]:
#NOW ORDERING THE ROWS IN THE SAME ORDER EVERYWHERE, FOR EXAMPLE INCREASING ORDER
GSE37754_df=GSE37754_df.sort_index()
GSE49149_df=GSE49149_df.sort_index()
GSE52068_df=GSE52068_df.sort_index()
GSE59157_df=GSE59157_df.sort_index()
GSE77955_df=GSE77955_df.sort_index()

In [79]:
#CREATE A DATAFRAME FROM THEM SINCE NOW ALL OF THEM HAS THE SAME CG SITES IN THE SAME ORDER
# List of DataFrames to concatenate
dfs = [GSE37754_df, GSE49149_df, GSE52068_df, GSE59157_df, GSE77955_df]
# Concatenate DataFrames along columns (axis=1)
betas_combined = pd.concat(dfs, axis=1)

In [80]:
betas_combined

,GSM927093,GSM927094,GSM927095,GSM927096,GSM927097,GSM927098,GSM927099,GSM927100,GSM927101,GSM927102,...,GSM2062402,GSM2062403,GSM2062404,GSM2062405,GSM2062406,GSM2062407,GSM2062408,GSM2062409,GSM2062410,GSM2062411
cg00000029,0.281969,0.344768,0.585868,0.322047,0.220112,0.231488,0.240406,0.204995,0.237319,0.282660,...,0.454866,0.399178,0.429116,0.423294,0.438061,0.359045,0.430449,0.438174,0.396768,0.443081
cg00000108,0.919281,0.918594,0.932110,0.915669,0.914480,0.929913,0.934619,0.928195,0.900301,0.914004,...,0.931314,0.917442,0.900366,0.912114,0.905101,0.917500,0.902444,0.507582,0.582373,0.504198
cg00000109,0.794163,0.786419,0.835731,0.769297,0.773373,0.870993,0.865093,0.812128,0.827515,0.751696,...,0.808670,0.808065,0.807984,0.809103,0.802373,0.813862,0.781382,0.829599,0.800881,0.828705
cg00000165,0.341791,0.343382,0.567962,0.332103,0.334977,0.628953,0.737022,0.617165,0.269565,0.297095,...,0.357305,0.266328,0.286442,0.344638,0.270489,0.352689,0.325080,0.305787,0.286025,0.294447
cg00000236,0.858880,0.842970,0.859775,0.835840,0.860427,0.889917,0.849441,0.876972,0.831325,0.840726,...,0.821092,0.803256,0.809615,0.740446,0.793900,0.806689,0.778259,0.798951,0.788009,0.799215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ch.9.98937537R,0.072251,0.068001,0.071651,0.070088,0.061230,0.066112,0.076829,0.066044,0.059819,0.072829,...,0.089520,0.088911,0.088042,0.084756,0.091030,0.081319,0.072635,0.089964,0.092282,0.084060
ch.9.98957343R,0.093288,0.082294,0.093929,0.091817,0.084161,0.077163,0.091055,0.072487,0.084322,0.094828,...,0.125026,0.108289,0.110321,0.109241,0.090371,0.116214,0.113774,0.110546,0.138267,0.120316
ch.9.98959675F,0.242242,0.239884,0.298533,0.292258,0.310823,0.195500,0.196733,0.247475,0.199370,0.229270,...,0.232840,0.197480,0.208827,0.192324,0.161398,0.212545,0.242177,0.284248,0.233239,0.219809
ch.9.98989607R,0.052723,0.044968,0.048350,0.053990,0.054009,0.044831,0.048929,0.047148,0.055349,0.055037,...,0.062421,0.054400,0.061471,0.049903,0.053678,0.054481,0.053935,0.072637,0.062057,0.059118
ch.9.991104F,0.205539,0.214985,0.202570,0.166541,0.241223,0.171689,0.172409,0.244579,0.206440,0.166143,...,0.184761,0.163802,0.187002,0.170704,0.156691,0.174767,0.175992,0.184581,0.169541,0.146135

In [ ]:
#NOW GET THE META OF THE DATA

df_cancer = pd.read_feather("../altumAge/cancer.arrow")
df_cancer_meta=df_cancer[['age','cancer','dataset', 'tissue_type', 'gender']]
df_cancer_meta=df_cancer_meta.T
df_cancer_meta=df_cancer_meta.drop(columns=['GSM1429560', 'GSM1429619']) #['GSM1429560', 'GSM1429619'] HERE THE AGE IS 144 SO DELETE THESE (IT CANT BE A CORRECT VALUE)

In [82]:
df_cancer_meta

,GSM801711,GSM801718,GSM801719,GSM801720,GSM801721,GSM801722,GSM801731,GSM801742,GSM801747,GSM801754,...,GSM927104,GSM927103,GSM927101,GSM927100,GSM927099,GSM927098,GSM927097,GSM927096,GSM927095,GSM927093
age,29.16,37.18,33.82,37.27,66.93,27.3,55.07,43.3,19.35,45.63,...,65.0,30.0,65.0,81.0,39.0,91.0,42.0,42.0,39.0,51.0
cancer,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
dataset,GSE32393,GSE32393,GSE32393,GSE32393,GSE32393,GSE32393,GSE32393,GSE32393,GSE32393,GSE32393,...,E-GEOD-39004,E-GEOD-39004,E-GEOD-39004,E-GEOD-39004,E-GEOD-39004,E-GEOD-39004,E-GEOD-39004,E-GEOD-39004,E-GEOD-39004,E-GEOD-39004
tissue_type,breast,breast,breast,breast,breast,breast,breast,breast,breast,breast,...,breast,breast,breast,breast,breast,breast,breast,breast,breast,breast
gender,F,F,F,F,F,F,F,F,F,F,...,F,F,F,F,F,F,F,F,F,F

In [83]:
geo_names_450k=list(GSE37754_df.columns)
geo_names_450k.extend(list(GSE49149_df.columns))
geo_names_450k.extend(list(GSE52068_df.columns))
geo_names_450k.extend(list(GSE59157_df.columns))
geo_names_450k.extend(list(GSE77955_df.columns))

In [ ]:
meta_450k=df_cancer_meta[list(set(geo_names_450k) & set(df_cancer_meta.columns))]
#THERE ARE SOME FROM FOR EXAMPLE IN THE GSE59157 WHERE NO AGE DATA IS ACCESSIBLE
#THESE WILL BE THE AGGREGATED DF-S COLNAMES, THE OTHERS WE DISCARD
meta_450k=df_cancer_meta[list(set(geo_names_450k) & set(df_cancer_meta.columns))] # somehow in the meta only 433 are from the 459 its 5%loss

In [85]:
betas_combined=betas_combined[ list(meta_450k.columns) ]

In [ ]:
#GSE59157 data is month instead of age (official altumAge meta is incorrect AGAIN)
valid_columns = meta_450k.columns.intersection(GSE59157_names)
#convert them to years (divide by 12)
meta_450k.loc['age', valid_columns] = meta_450k.loc['age', valid_columns] / 12

/tmp/ipykernel_2382394/776998397.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta_450k.loc['age', valid_columns] = meta_450k.loc['age', valid_columns] / 12

In [114]:
meta_450k

,GSM927098,GSM1435226,GSM927136,GSM1258213,GSM1194476,GSM1429553,GSM1194434,GSM1429602,GSM1194449,GSM2062403,...,GSM1429594,GSM1429546,GSM2062409,GSM1194457,GSM1194371,GSM1194503,GSM1194413,GSM1429548,GSM1435240,GSM927111
age,91.0,58.0,63.0,26.0,72.0,3.916667,57.0,3.5,75.0,71.0,...,3.666667,3.5,57.0,76.0,64.0,69.0,68.0,1.916667,62.0,62.0
cancer,1,1,1,0,1,0,1,1,1,0,...,1,0,0,1,1,1,1,0,0,1
dataset,E-GEOD-39004,E-GEOD-49149,E-GEOD-39004,E-GEOD-52068,E-GEOD-49149,GSE59157,E-GEOD-49149,GSE59157,E-GEOD-49149,E-GEOD-77955,...,GSE59157,GSE59157,E-GEOD-77955,E-GEOD-49149,E-GEOD-49149,E-GEOD-49149,E-GEOD-49149,GSE59157,E-GEOD-49149,E-GEOD-39004
tissue_type,breast,pancreas,breast,nasopharyngeal,pancreas,kidney,pancreas,kidney,pancreas,colon,...,kidney,kidney,liver,pancreas,pancreas,pancreas,pancreas,kidney,pancreas,breast
gender,F,F,F,M,F,M,M,M,F,M,...,M,M,M,M,M,F,F,F,M,F

In [ ]:
#save the aggregated dataframes, from now on I call it altumAge450k
betas_combined.to_csv('altumAge450k_beta.csv')
meta_450k.to_csv('altumAge450k_meta.csv')