In [ ]:
def all_lists_equal(lst):
    return all(sublist == lst[0] for sublist in lst)

def create_dataframe(data, col_names, row_names):
    df = pd.DataFrame({col_names[i]: data[i] for i in range(len(col_names))}, index=row_names)
    return df

In [ ]:
import pandas as pd
#run time 5min

file_path = 'GSE37754_family.soft'

sample_geo = []
sample_cgs=[]
sample_betas=[]
is_beta=False

with open(file_path, 'r') as file:
    for line in file:
        # Check for sample ID line
        if(is_beta==False):
            if line.startswith('^SAMPLE = '):
                current_geo = line.strip().split('= ')[-1]
                sample_geo.append(current_geo)
        
            elif line.startswith('ID_REF	VALUE'):
                actual_betas=[]
                actual_cgs=[]
                is_beta=True
        else:
            if line.startswith('!sample_table_end'):
                sample_cgs.append(actual_cgs)
                sample_betas.append(actual_betas)
                is_beta=False
            else:
                elements=line.strip().split('\t')
                actual_cgs.append(elements[0]) 
                actual_betas.append(elements[1])

In [ ]:
#print(all_lists_equal(sample_cgs)) #so now we can create dataframe since the order and sites are the same
GSE37754_df = create_dataframe(sample_betas, sample_geo, sample_cgs[0])
#THESE BETA VALUES ARENT NORMALIZED YET, THEY MUST BE CONVERTED FROM M-VALUES TO BETA VALUES
GSE37754_df.to_csv('GSE37754_betas_NOT NORMALIZED.csv')

In [ ]:
import pandas as pd
#run time 5min

file_path = 'GSE49149_family.soft'

sample_geo = []
sample_cgs=[]
sample_betas=[]
is_beta=False

with open(file_path, 'r') as file:
    for line in file:
        # Check for sample ID line
        if(is_beta==False):
            if line.startswith('^SAMPLE = '):
                current_geo = line.strip().split('= ')[-1]
                sample_geo.append(current_geo)
        
            elif line.startswith('ID_REF	VALUE'):
                actual_betas=[]
                actual_cgs=[]
                is_beta=True
        else:
            if line.startswith('!sample_table_end'):
                sample_cgs.append(actual_cgs)
                sample_betas.append(actual_betas)
                is_beta=False
            else:
                elements=line.strip().split('\t')
                actual_cgs.append(elements[0]) 
                actual_betas.append(elements[1])

In [ ]:
#print(all_lists_equal(sample_cgs)) #True so now we can create dataframe since the order and sites are the same
GSE49149_df = create_dataframe(sample_betas, sample_geo, sample_cgs[0])
GSE49149_df.to_csv('GSE49149_betas.csv') 
GSE49149_df

,GSM1194354,GSM1194355,GSM1194356,GSM1194357,GSM1194358,GSM1194359,GSM1194360,GSM1194361,GSM1194362,GSM1194363,...,GSM1435236,GSM1435237,GSM1435238,GSM1435239,GSM1435240,GSM1435241,GSM1435242,GSM1435243,GSM1435244,GSM1435245
cg00000165,0.236761977,0.603708038,0.257132812,0.436311675,0.206783456,0.515761791,0.48362313,0.529192407,0.291585155,0.348704103,...,0.333840528,0.702609844,0.232593583,0.603617845,0.36765872,0.430335122,0.31689469,0.489438543,0.495621874,0.669205364
cg00000363,0.37734014,0.20712197,0.319522028,0.317945082,0.208538766,0.38880596,0.246521855,0.205115129,0.149752251,0.288417322,...,0.260590944,0.241387023,0.292887785,0.207016736,0.327046429,0.374893153,0.291770724,0.277487225,0.396474559,0.226383126
cg00001349,0.602949217,0.765146527,0.645981894,0.692175078,0.476377931,0.784771396,0.718438244,0.701745353,0.648234515,0.747132965,...,0.613090068,0.764720703,0.694223081,0.662037229,0.718451663,0.758896183,0.752839853,0.695289308,0.687876321,0.795855953
cg00001364,0.798663511,0.833834854,0.858607305,0.861442447,0.842142653,0.842315614,0.842969767,0.844238389,0.813556886,0.835702303,...,0.853378551,0.848106245,0.827197852,0.848142926,0.827054156,0.823720692,0.804923285,0.781118644,0.873435419,0.881700914
cg00001446,0.885168661,0.735939333,0.853466277,0.852774323,0.861009317,0.655330387,0.845422527,0.806148627,0.849831385,0.850885208,...,0.815771214,0.666461047,0.808623542,0.82110763,0.776037905,0.827567265,0.79008424,0.818410666,0.679731128,0.642940356
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ch.22.44116734F,0.068453356,0.076006821,0.10555043,0.061835872,0.063501567,0.068143358,0.08242994,0.033630527,0.109675999,0.0704478,...,0.068953871,0.049668316,0.047159447,0.074957535,0.067626123,0.051250308,0.060258508,0.095945344,0.058736537,0.062190431
ch.22.909671F,0.200480248,0.088707353,0.261597669,0.165917225,0.173620496,0.143704301,0.170898882,0.104562093,0.289368636,0.193182665,...,0.250309493,0.12191731,0.107376783,0.096034102,0.116085633,0.092377145,0.090512388,0.134926214,0.090921843,0.165952121
ch.22.46830341F,0.039519379,0.035543004,0.043136684,0.026021322,0.045854737,0.036569026,0.047656487,0.043304669,0.041675555,0.037634104,...,0.043929154,0.056436159,0.059250202,0.052997263,0.060427716,0.053350935,0.070955048,0.051797279,0.047677922,0.048267004
ch.22.1008279F,0.023339791,0.020927258,0.028596747,0.031319065,0.033392902,0.032161091,0.030877904,0.028209932,0.018779294,0.027857038,...,0.027154268,0.019167591,0.022816696,0.026516818,0.028000091,0.014261394,0.028424018,0.029237667,0.037615038,0.032543105
ch.22.47579720R,0.045688284,0.082268315,0.067552603,0.073293611,0.062525658,0.070119772,0.083721968,0.071608239,0.090829029,0.128657122,...,0.131782997,0.105545266,0.124373322,0.144400414,0.113654672,0.088781462,0.108061208,0.120004998,0.096367198,0.102988746

In [ ]:
import pandas as pd
#run time 5min

file_path = 'GSE52068_family.soft'

sample_geo = []
sample_cgs=[]
sample_betas=[]
is_beta=False

with open(file_path, 'r') as file:
    for line in file:
        # Check for sample ID line
        if(is_beta==False):
            if line.startswith('^SAMPLE = '):
                current_geo = line.strip().split('= ')[-1]
                sample_geo.append(current_geo)
        
            elif line.startswith('ID_REF	VALUE'):
                actual_betas=[]
                actual_cgs=[]
                is_beta=True
        else:
            if line.startswith('!sample_table_end'):
                sample_cgs.append(actual_cgs)
                sample_betas.append(actual_betas)
                is_beta=False
            else:
                elements=line.strip().split('\t')
                actual_cgs.append(elements[0]) 
                actual_betas.append(elements[1])

In [ ]:
#print(all_lists_equal(sample_cgs)) #so now we can create dataframe since the order and sites are the same
GSE52068_df = create_dataframe(sample_betas, sample_geo, sample_cgs[0])
GSE52068_df.to_csv('GSE52068_betas.csv')
GSE52068_df

,GSM1258183,GSM1258184,GSM1258185,GSM1258186,GSM1258187,GSM1258188,GSM1258189,GSM1258190,GSM1258191,GSM1258192,...,GSM1258221,GSM1258222,GSM1258223,GSM1258224,GSM1258225,GSM1258226,GSM1258227,GSM1258228,GSM1258229,GSM1258230
cg00000029,0.57483913,0.384654995,0.620099627,0.499900513,0.515012531,0.226802932,0.336797794,0.212374674,0.16899997,0.573463906,...,0.500539297,0.430555442,0.479986192,0.516204162,0.573389657,0.453164431,0.618539782,0.565565904,0.471812181,0.539734481
cg00000108,0.896455596,7.77E-07,0.905052475,0.925226704,0.897789694,0.920322297,0.921051332,0.903951832,0.907559162,0.913987818,...,0.935464773,0.868151402,0.889514237,0.941409333,0.909260158,0.911823187,0.958580281,0.908241829,0.91320463,0.901383915
cg00000109,0.82788534,0.829778451,0.828555676,0.797083288,0.871862902,0.805351569,0.84227954,0.843694604,0.883402616,0.796032766,...,0.809938367,0.845835094,0.81333659,0.806271859,0.840742434,0.820110246,0.794270305,0.793600249,0.818773205,0.803841106
cg00000165,0.165489789,0.44443776,0.281419977,0.269409696,0.346994726,0.59735916,0.641291578,0.498059302,0.612771121,0.274991045,...,0.237820235,0.227891482,0.269206773,0.259550657,0.253583601,0.249590303,0.267963949,0.291842256,0.308072717,0.299187808
cg00000236,0.849449782,0.861773164,0.853722089,0.869762305,0.862614165,0.832589568,0.880200886,0.864859109,0.853492427,0.878661497,...,0.855590435,0.862767886,0.84338076,0.838690198,0.813718978,0.865761692,0.873231243,0.862929453,0.835023231,0.878068518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rs9363764,0.424851541,0.469254995,0.040130644,0.493123462,0.911893861,0.904157988,0.479325868,0.920197841,0.322958722,0.488071716,...,0.077820938,0.502387556,0.940756569,0.02210495,0.47864527,0.500332993,0.483966322,0.938270786,0.500740414,0.914817193
rs939290,0.51994712,0.342945383,0.557891232,0.51954754,0.925639217,0.179936782,0.505463451,0.3668712,0.655116756,0.953129465,...,0.929862138,0.955755237,0.485794119,0.953874527,0.957533991,0.527819991,0.476482969,0.001579602,0.030076512,0.523165225
rs951295,0.038823264,0.059215004,0.054537817,0.927513834,0.925649727,0.911442479,0.450756382,0.93783725,0.302563218,0.040950373,...,0.076580818,0.93535281,0.940477139,0.470760206,0.901488451,0.946053492,0.478986564,0.488780092,0.500917122,0.900071059
rs966367,2.04E-05,0.388147516,0.000432051,1.08E-07,0.212248835,0.195410993,0.355147772,0.177889928,-4.53E-06,-1.44E-05,...,0.439602239,0.420779524,0.412747675,-2.51E-05,1.80E-05,0.433868082,0.00016074,-4.22E-05,0.945318866,0.39874429
rs9839873,0.94109439,0.927899248,0.949558329,0.94269335,0.923437296,0.922083958,0.962021841,0.955959583,0.944905595,0.946951238,...,0.960801015,0.957042358,0.945035268,0.964838461,0.956860482,0.944574956,0.938554876,0.588120085,0.943313911,0.932973217

In [ ]:
import pandas as pd
#run time 5min

file_path = 'GSE59157_family.soft'

sample_geo = []
sample_cgs=[]
sample_betas=[]
is_beta=False

with open(file_path, 'r') as file:
    for line in file:
        # Check for sample ID line
        if(is_beta==False):
            if line.startswith('^SAMPLE = '):
                current_geo = line.strip().split('= ')[-1]
                sample_geo.append(current_geo)
        
            elif line.startswith('ID_REF	VALUE'):
                actual_betas=[]
                actual_cgs=[]
                is_beta=True
        else:
            if line.startswith('!sample_table_end'):
                sample_cgs.append(actual_cgs)
                sample_betas.append(actual_betas)
                is_beta=False
            else:
                elements=line.strip().split('\t')
                actual_cgs.append(elements[0]) 
                actual_betas.append(elements[1])

In [ ]:
#print(all_lists_equal(sample_cgs)) #True so now we can create dataframe since the order and sites are the same
GSE59157_df = create_dataframe(sample_betas, sample_geo, sample_cgs[0])
GSE59157_df.to_csv('GSE59157_betas.csv')
GSE59157_df

,GSM1429528,GSM1429529,GSM1429530,GSM1429531,GSM1429532,GSM1429533,GSM1429534,GSM1429535,GSM1429536,GSM1429537,...,GSM1429613,GSM1429614,GSM1429615,GSM1429616,GSM1429617,GSM1429618,GSM1429619,GSM1429620,GSM1429621,GSM1429622
cg00000029,0.321882027,0.420860444,0.40094873,0.595341763,0.429466109,0.320516427,0.248992716,0.431891032,0.417823766,0.531289223,...,0.320421334,0.274833798,0.338964039,0.550746553,0.325005187,0.600381915,0.190374543,0.43547321,0.242519281,0.69234886
cg00000108,0.912291225,0.87452043,0.872644165,0.8684039,0.827498569,0.845625794,0.874710588,0.855300239,0.847753493,0.872536702,...,0.816454515,0.869788536,0.857305318,0.883197972,0.865912151,0.901529026,0.825888683,0.934489075,0.92315189,0.910062834
cg00000109,0.76338886,0.840998038,0.780880675,0.824649752,0.822585996,0.847445229,0.822767509,0.764303752,0.868152489,0.869366398,...,0.69950508,0.839648286,0.815011174,0.820267528,0.832040781,0.871142711,0.804693206,0.858926505,0.817152628,0.850383567
cg00000165,0.19384631,0.170858655,0.27235939,0.33135811,0.203697538,0.279365317,0.254883899,0.198554787,0.176425942,0.222229714,...,0.318195327,0.214970188,0.11851296,0.313826427,0.258997572,0.211822079,0.239920981,0.532084935,0.234138461,0.19063562
cg00000236,0.724747475,0.736467617,0.658260176,0.660295063,0.6673423,0.67259435,0.68977494,0.744483018,0.613173226,0.762457522,...,0.747836819,0.746666748,0.724840366,0.760584016,0.677340082,0.80156054,0.762691345,0.787233104,0.744414507,0.749482451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ch.X.97129969R,0.125403837,0.100102548,0.148806,0.088892953,0.096036351,0.1260324,0.154214486,0.108038812,0.049145781,0.060647868,...,0.190260962,0.171992901,0.109541089,0.096059595,0.116304683,0.068649686,0.14779213,0.083092348,0.059171656,0.05657008
ch.X.97133160R,0.158403652,0.197376768,0.222063371,0.175069644,0.12208198,0.143310145,0.158892535,0.116754149,0.413804861,0.168503698,...,0.236878692,0.158216777,0.240425739,0.156963564,0.179888983,0.205710463,0.195798793,0.134365372,0.150566693,0.106943581
ch.X.97651759F,0.113471846,0.050944086,0.134021582,0.119490247,0.052093564,0.101464315,0.123254989,0.101711,0.077224796,0.092050284,...,0.195669713,0.048106555,0.109916483,0.056829616,0.086810874,0.071051902,0.098936588,0.111855031,0.089534606,0.069111679
ch.X.97737721F,0.125182113,0.140950566,0.311123886,0.155517028,0.196851547,0.182681447,0.218650908,0.139508354,0.184148582,0.173648032,...,0.255339757,0.125624982,0.137742556,0.121819333,0.173811907,0.127812704,0.150935506,0.117159247,0.102796398,0.114740469
ch.X.98007042R,0.102387464,0.163256797,0.195700613,0.200587452,0.140942258,0.16348976,0.223390199,0.128266754,0.099428617,0.194092843,...,0.22558307,0.185106471,0.168042821,0.162446512,0.188364542,0.182222925,0.196951647,0.120596352,0.119320933,0.158363243

In [ ]:
import pandas as pd
#run time 5min

file_path = 'GSE77955_family.soft'

sample_geo = []
sample_cgs=[]
sample_betas=[]
is_beta=False

with open(file_path, 'r') as file:
    for line in file:
        # Check for sample ID line
        if(is_beta==False):
            if line.startswith('^SAMPLE = '):
                current_geo = line.strip().split('= ')[-1]
                sample_geo.append(current_geo)
        
            elif line.startswith('ID_REF	VALUE'):
                actual_betas=[]
                actual_cgs=[]
                is_beta=True
        else:
            if line.startswith('!sample_table_end'):
                sample_cgs.append(actual_cgs)
                sample_betas.append(actual_betas)
                is_beta=False
            else:
                elements=line.strip().split('\t')
                actual_cgs.append(elements[0]) 
                actual_betas.append(elements[1])

#this is the aggregated data of two measurements so the first 58 is measured with another method so irrelevant for us
#the first 58 should be deleted from every list
sample_geo = sample_geo[58:]          
sample_cgs = sample_cgs[58:]    
sample_betas = sample_betas[58:]

In [ ]:
#print(all_lists_equal(sample_cgs)) #True so now we can create dataframe since the order and sites are the same
GSE77955_df = create_dataframe(sample_betas, sample_geo, sample_cgs[0])
GSE77955_df.to_csv('GSE77955_betas_NOT_NORMALIZED.csv') # this is the unnormalized data, should be converted to beta values from m-values
GSE77955_df

,GSM2062364,GSM2062365,GSM2062366,GSM2062367,GSM2062368,GSM2062369,GSM2062370,GSM2062371,GSM2062372,GSM2062373,...,GSM2062402,GSM2062403,GSM2062404,GSM2062405,GSM2062406,GSM2062407,GSM2062408,GSM2062409,GSM2062410,GSM2062411
cg13869341,2.47828216939372,2.69608537310075,2.33522505413935,1.95688825969257,1.7463515397481,3.45642278581173,2.84735246618383,3.2765099775019,2.94332871534468,2.62681554790141,...,2.68210208542689,3.27830682055726,2.39255070548527,2.30826952853586,3.2731292927367,2.21874156571944,2.46805689905797,2.0026858656728,2.3451541545766,2.71344234642133
cg14008030,1.23138093337051,1.37200329909941,1.30014308811978,2.08424292402071,1.77428219417906,1.13371916502442,0.777962248616708,1.0825940030013,1.20426210677395,1.08107156654842,...,0.932132429887062,1.12077638790707,1.13940391264157,1.45962853325797,1.34665895169073,0.893040237756765,1.6401351429962,1.47939735660174,1.63905221365113,1.50036443334849
cg12045430,-2.51276618724849,-1.89587637655761,-2.15853249954174,-2.10937808133676,-1.59929090284119,-2.08266240952725,-2.56941950251333,-2.06768275739994,-2.85336580127441,-2.6319485307067,...,-2.8427486009859,-2.6152623360118,-2.76005685663071,-2.79610246222805,-3.13955639160757,-2.68899714195953,-3.09831195619181,-2.92619555895595,-3.09841704927533,-3.49957662197575
cg20826792,-1.57080843037979,-1.4334821585794,-1.37852020213605,-1.45655531797067,-1.20187830207036,-1.23845833253474,-1.61110946092034,-1.77125598221106,-1.67612351539032,-1.02946933333378,...,-1.58217984052825,-1.64810403573953,-1.67904470565278,-1.59991825367755,-1.81561535741793,-1.63732295366365,-1.69727163909115,-1.54072114258306,-1.7335417258307,-1.80451804094309
cg00381604,-3.91460158336293,-3.19817274185087,-3.62766116998442,-3.40604053336134,-3.23866786523203,-3.5749543332208,-3.99164890882237,-3.86414154689361,-3.80528861917833,-3.48944322136663,...,-3.81858946069577,-3.11151219325946,-4.03837763895055,-3.28221757688051,-3.57625964281168,-3.24383149166038,-3.97131216898816,-3.54480679196163,-3.47025455355464,-3.73077093872996
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cg17939569,-0.113267456080371,-0.44204269214857,0.828879509519076,0.197743272776277,0.71916126388965,0.339439680214087,0.668031723161191,-0.225021875214764,0.205292566646952,0.471970276235923,...,1.30302597095583,1.09254136385172,1.13358015990862,1.02715245948384,0.215240670664989,-0.238460995436998,1.11066785462019,0.812382675308771,0.827495880169957,0.58441519170474
cg13365400,0.0600835423340617,0.982116213604636,1.88133567559163,0.288153605812277,1.41429985316721,0.608985148518912,0.20241097979836,0.788525995258529,0.719385983093776,1.33657608555364,...,1.02705962526886,1.11738242672725,0.88313097620755,1.52690313492182,-0.0818165312268124,0.142444090993256,1.23399868943866,1.58207942038418,1.60108637667562,2.06200337856664
cg21106100,2.4146528051057,2.65838713960975,2.22969639856531,-0.264804991528719,2.02268337750895,-0.230553077251047,2.48673681700577,2.12952737334211,2.50942915653436,1.0473180628554,...,2.67249005863084,2.09359169507043,2.24007737361384,1.91569760220732,-0.547684084170242,0.0348529480808049,2.30975931752106,1.26566913195497,1.68234820570335,2.09393364708436
cg08265308,3.15288589921699,3.03213048812108,3.28101705227318,-0.171231524157619,2.77617393919628,-0.23813259581476,3.38003395884566,3.17315659569536,2.79141650283208,2.47729016368403,...,2.93315312086936,2.61001949815431,2.81124564171357,2.43571985694127,-0.790225199180422,-0.314488580994819,2.67512238309821,1.8300197086178,2.77158564616469,2.70844735258466
cg14273923,2.16055403481977,1.83292588322184,2.4241458332014,-0.0667591255623384,2.35115736330737,-0.0856875965480439,1.62109798972236,2.26160351035934,2.04766395854259,2.47569643302421,...,1.34780809078774,1.77462930109131,1.48644865237645,1.57138031751774,-0.296024541161947,0.019414848382831,1.67844242804138,0.127089464993306,1.55704249550764,1.39820636505109

In [ ]:
# count nans before beta value conversion (it would cause error)
# Convert all values to float, replacing errors with NaN
GSE37754_df = GSE37754_df.apply(pd.to_numeric, errors='coerce')
# Count total NaN values
nan_count = GSE37754_df.isna().sum().sum()
print(f"Total NaN values in the DataFrame: {nan_count}")

Total NaN values in the DataFrame: 0

In [ ]:
# count nans before beta value conversion (it would cause error)
# Convert all values to float, replacing errors with NaN
GSE77955_df = GSE77955_df.apply(pd.to_numeric, errors='coerce')
# Count total NaN values
nan_count = GSE77955_df.isna().sum().sum()
print(f"Total NaN values in the DataFrame: {nan_count}")

Total NaN values in the DataFrame: 0

In [ ]:
# Convert M-values to Beta values
def m_to_beta(m_values):
    return 2**m_values / (2**m_values + 1)

# Apply the function to the entire dataframe
GSE37754_df_beta = GSE37754_df.apply(m_to_beta)
GSE77955_df_beta = GSE77955_df.apply(m_to_beta)
#now we can save the beta values to csv files
GSE37754_df_beta.to_csv('GSE37754_betas.csv')
GSE77955_df_beta.to_csv('GSE77955_betas.csv')